#!/usr/bin/env python3
"""Package the chart-ready CSVs as local JavaScript for the offline dashboard."""

from __future__ import annotations

import csv
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_DATA_DIR = PROJECT_ROOT / "data/dashboard"
SITE_DIR = PROJECT_ROOT / "dashboard_site"
OUTPUT_PATH = SITE_DIR / "dashboard-data.js"
FILES = (
    "national_quarterly_payments_context.csv",
    "national_annual_cash_reliance.csv",
    "national_payment_mix_quarterly.csv",
    "state_scale_growth_business_signals.csv",
)


def load_csv(filename: str) -> list[dict[str, str]]:
    path = DASHBOARD_DATA_DIR / filename
    if not path.is_file():
        raise FileNotFoundError(f"Missing dashboard data file: {path}")
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    payload = {filename.removesuffix(".csv"): load_csv(filename) for filename in FILES}
    manifest_path = DASHBOARD_DATA_DIR / "dashboard_data_manifest.json"
    payload["manifest"] = json.loads(manifest_path.read_text(encoding="utf-8"))
    OUTPUT_PATH.write_text(
        "// Generated by scripts/build_dashboard_site.py. Do not edit by hand.\n"
        f"window.UPI_DASHBOARD_DATA = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"Created {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
